[ADD] estate:  Added basic structure and default views of the module
odoo/tutorials pull request #217
Opened 2024-12-17 12:52 UTC by chdh-odoo

Created the estate_property table to store property details and granted
full access to base.group_user for this table. Default list and form views
have been added.

![image](https://github.com/user-attachments/assets/97a02123-e062-411c-8aa9-221a5363694c)

2024-12-17 12:52 UTC, robodoo commented
[![Pull request status dashboard](https://mergebot.odoo.com/odoo/tutorials/pull/217.png)](https://mergebot.odoo.com/odoo/tutorials/pull/217)

2024-12-19 07:01 UTC, aktr-odoo requested changes
Hello,
I have added a few comments. Can you please have a look?

2024-12-19 09:10 UTC, chdh-odoo commented on estate/__manifest__.py
> +    "description": "Real estate module for managing property listings and transactions!",
Sure

2024-12-20 04:36 UTC, chdh-odoo commented on estate/models/estate_property.py
> +
Removed

2024-12-20 04:37 UTC, chdh-odoo commented on estate/views/estate_property_type_views.xml
> +    <!-- Default View -->
I have updated comment to "action window for managing property"

2024-12-20 04:38 UTC, chdh-odoo commented on estate/views/estate_property_views.xml
> +<record id="estate_property_action" model="ir.actions.act_window">
Sure, I have Improved formating in each file.

2024-12-30 12:41 UTC, aktr-odoo requested changes
Hello, a few more comments

2024-12-30 12:41 UTC, aktr-odoo commented on estate/security/ir.model.access.csv
> +access_estate_property_offer_user, estate.property.offer,model_estate_property_offer,estate.estate_group_user,1,1,1,1
```suggestion
access_estate_property_manager,estate.property,model_estate_property,estate.estate_group_manager,1,1,1,0
access_estate_property_user,estate.property,model_estate_property,estate.estate_group_user,1,1,1,0
access_estate_property_type_manager, estate.property.type,model_estate_property_type,estate.estate_group_manager,1,1,1,1
access_estate_property_type_user, estate.property.type,model_estate_property_type,estate.estate_group_user,1,0,0,0
access_estate_property_tag_manager, estate.property.tag,model_estate_property_tag,estate.estate_group_manager,1,1,1,1
access_estate_property_tag_user,estate.property.tag,model_estate_property_tag,estate.estate_group_user,1,0,0,0
access_estate_property_offer_manager, estate.property.offer,model_estate_property_offer,estate.estate_group_manager,1,1,1,1
access_estate_property_offer_user, estate.property.offer,model_estate_property_offer,estate.estate_group_user,1,1,1,1
```

2024-12-30 12:41 UTC, aktr-odoo commented on estate/views/estate_property_views.xml
> +                            <p t-if="record.state.raw_value==='offer_received' || record.state.raw_value==='offer_accepted' || record.state.raw_value==='sold'">Best Price: <field name="best_price"/><
too long line

2024-12-31 12:42 UTC, chdh-odoo commented on estate/models/estate_property_tag.py
> +    _order = "create_date desc"
Sure, I will keep  _order on top in each model.

2025-01-16 05:20 UTC, closed without merging